### ISSUE TITLE
Trying to figure out current option for Listbox

### ISSUE THREAD

**Issue by nXecure** [martynets/dialogbox#2]
Sorry to disturb you again.

I am trying to figure out how the **current** options works with listboxes.
I can easily add it during the list creation, such as:
`add item "Item 1" current`
But when trying to select the current item from outside the listbox, I find that nothing works.
Based on the set option:
> **`set [name] options [text]`**
> - `current` - makes item of a list widget or tab (page widget) of a tabs widget the current one.

I imagine that it would be similar to:
`set LISTBOX_NAME current "item 2"`
and even with the position
`set LISTBOX_NAME current 2`
but I am not able to get it to work.

Could you give me a hint of the correct format of the command? I tested on both qt4 and qt5 versions and wasn't to get it to work.

Thanks for your time.

**Comment by nXecure** [comment]
Sorry for bringing this up. I re-read the README and found the information I needed in the add istem section

> This text can also be used to address the item in format `<list_widget_name>:<item_text>`.

So it would look like:
`set "LISTBOX_NAME:Item 2" current`

Sorry. And thanks for the fantastic work!

**Comment by martynets** [comment]
Hi nXecure,
I'm glad that my manual helps.
Thank you!
