### ISSUE TITLE
Windows Release

### ISSUE THREAD

**Issue by darkphase** [martynets/dialogbox#4]
Is it possible to compile project for Windows? 
And put it to release page with other OS releases.
As of now there seems no package released yet...

**Comment by martynets** [comment]
First of all thanks for your interest to this project!
It is pure QT project and thus it is expected to be buildable for any platform supported by QT. As far as I know Windows is supported. However, never tried.
This project is released as package of sources what is common for Linux world. I'm sure this will work for Windows as well if you install QT for Windows and follow the respective instructions.
Thank you!
